permissions:
  id-token: write
  contents: read

name: AWS Signal on Push

on:
  push:
    branches:
      - "*"

jobs:
  send_signal:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up OIDC for AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: eu-central-1

    - name: Send message to SQS
      run: |
        aws sqs send-message --queue-url https://sqs.eu-central-1.amazonaws.com/314146309237/queue.fifo --message-group-id 1 --message-deduplication-id 1 --message-body "Push on branch ${{ github.ref }}"
